export const departments = ["Air Conditioning Systems",
    "Building Security",
    "Building structure maintenance",
    "Car parking",
    "Catering",
    "Cleaning service",
    "Decoration and refurbishment",
    "Document management",
    "Electricity",
    "Fire Safety",
    "Furniture and equipment",
    "Gardening service",
    "Ground maintenance",
    "Heating systems",
    "Information systems / Internet",
    "Lift and Escalator",
    "Natural Gas",
    "Painting",
    "Pest control",
    "Plumbing and draining",
    "Printing",
    "Reception services",
    "Recycling",
    "Space management",
    "TV cable",
    "Water Management",
    "Other"
]